#!/bin/sh
### BEGIN INIT INFO
# Provides:          minio
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start MinIO Server
# Description:       Controls MinIO as a service
### END INIT INFO

MINIO_BIN="/usr/local/bin/minio"
MINIO_OPTS="--console-address :9001 /home/runner/minio"
MINIO_USER="runner"
MINIO_LOG="/var/log/minio.log"

start() {
    echo "Starting MinIO..."
    start-stop-daemon --start --background --make-pidfile --pidfile /var/run/minio.pid \
        --chuid $MINIO_USER --exec $MINIO_BIN -- server $MINIO_OPTS >> $MINIO_LOG 2>&1
    echo "MinIO started."
}

stop() {
    echo "Stopping MinIO..."
    start-stop-daemon --stop --pidfile /var/run/minio.pid
    echo "MinIO stopped."
}

status() {
    if [ -f /var/run/minio.pid ]; then
        echo "MinIO is running with PID $(cat /var/run/minio.pid)."
    else
        echo "MinIO is not running."
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
exit 0
